[package]
name = "pwbimonitor"
version = "0.1.0"
edition = "2024"

[dependencies]
dns-lookup = "2.0.4"
etherparse = "0.17.0"
httparse = "1.10.1"
pcap = "2.2.0"
pnet = "0.35.0"
serde_json = "1.0.140"
stdnet = "0.0.0"
